"""Storage port protocol for persistence operations."""

from datetime import date
from typing import TYPE_CHECKING, Protocol

if TYPE_CHECKING:
    from tpy_lipi.core.models import DailyNote, Topic


class StoragePort(Protocol):
    """Protocol for storage operations - topics and daily notes."""

    # Topic operations
    def save_topic(self, topic: "Topic") -> None: ...
    def get_topic(self, name: str) -> "Topic | None": ...
    def get_all_topics(self) -> list["Topic"]: ...
    def get_recent_topics(self, days: int = 14) -> list["Topic"]: ...
    def delete_topic(self, name: str) -> None: ...

    # DailyNote operations
    def save_daily_note(self, note: "DailyNote") -> None: ...
    def get_daily_note(self, note_date: date) -> "DailyNote | None": ...
    def get_daily_notes_range(self, start: date, end: date) -> list["DailyNote"]: ...
